service: aws-sls-tester
app: aws-sls-tester
org: st3v3nhunt

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal-profile
  iamRoleStatements:
  - Effect: Allow
    Action:
    - sqs:SendMessage
    Resource:
    - Fn::GetAtt: [ MyQ, Arn ]

functions:
  echo:
    handler: handler.echo
    events:
    - http:
        path: echo
        method: post
  processQ:
    handler: handler.processQ
    events:
    - sqs:
        arn:
          Fn::GetAtt:
            - MyQ
            - Arn

resources:
  Resources:
    MyQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyQueue-${opt:stage}
