service: aws-sls-tester
app: aws-sls-tester
org: st3v3nhunt

provider:
  name: aws
  runtime: nodejs12.x
  profile: personal-profile
  iamRoleStatements:
  - Effect: Allow
    Action:
    - sqs:SendMessage
    Resource:
    - Fn::GetAtt: [ MyQ, Arn ]
  - Effect: Allow
    Action:
    - s3:PutObject
    - s3:GetObject
    Resource:
      Fn::Join:
        - ''
        - - 'arn:aws:s3:::'
        - Ref: ${self:custom.queue}


functions:
  submit:
    handler: handler.submit
    events:
    - http:
        path: submit
        method: post
    environment:
      QUEUE_NAME: ${self:custom.queue}
  process:
    handler: handler.process
    events:
    - sqs:
        arn:
          Fn::GetAtt:
            - MyQ
            - Arn
    environment:
      BUCKET: ${self:custom.bucket}
  view:
    handler: handler.view
    events:
    - http:
        path: view
        method: get
    environment:
      BUCKET: ${self:custom.bucket}

resources:
  Resources:
    MyQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queue}

custom:
  bucket: aws-lmda-test-bucket
  queue: MyQueue-${opt:stage}
